const canvas=document.getElementById('game');
const ctx=canvas.getContext('2d');
let W=innerWidth,H=innerHeight,DPR=1;
function resize(){DPR=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=Math.floor(W*DPR);canvas.height=Math.floor(H*DPR);canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(DPR,0,0,DPR,0,0);if(player){player.x=Math.min(Math.max(player.x,30),W-30);player.y=Math.min(Math.max(player.y,30),H-30)}}
addEventListener('resize',resize);
const $=id=>document.getElementById(id);
const keys={};const mouse={x:innerWidth/2,y:innerHeight/2,down:false};
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(e.key.toLowerCase()))e.preventDefault();if((e.key==='Enter')&&state!=='playing')startGame()});
addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
canvas.addEventListener('mousemove',e=>{mouse.x=e.clientX;mouse.y=e.clientY});canvas.addEventListener('mousedown',()=>mouse.down=true);addEventListener('mouseup',()=>mouse.down=false);
const rand=(a,b)=>Math.random()*(b-a)+a;
let state='playing',last=0,timeAlive=0,wave=1,kills=0,waveKills=0,spawnTimer=.1,shake=0,xp=0,xpNeed=40,msgTimer=0,msg='';
let player={x:W/2,y:H/2,r:19,hp:100,maxHp:100,speed:245,damage:30,range:82,attackCd:0,attackRate:.32,dashCd:0,dashMax:1.2,special:0,inv:0,crit:.08};
let enemies=[],particles=[],slashes=[],shots=[],floats=[],stars=[];
for(let i=0;i<180;i++)stars.push({x:Math.random(),y:Math.random(),s:Math.random()*2+.3,a:Math.random()*.55+.15});
resize();
function startGame(){state='playing';timeAlive=0;wave=1;kills=0;waveKills=0;spawnTimer=.1;xp=0;xpNeed=40;enemies=[];particles=[];slashes=[];shots=[];floats=[];player={x:W/2,y:H/2,r:19,hp:100,maxHp:100,speed:245,damage:30,range:82,attackCd:0,attackRate:.32,dashCd:0,dashMax:1.2,special:0,inv:0};hideScreens();message('WAVE 1',1)}
function hideScreens(){for(const id of ['startScreen','gameOver','upgradeScreen']){const el=$(id);if(el)el.classList.add('hidden')}}
function message(t,d=1){msg=t;msgTimer=d}
function spawnEnemy(){const side=Math.floor(Math.random()*4),m=60;let x=0,y=0;if(side===0){x=rand(-m,W+m);y=-m}else if(side===1){x=W+m;y=rand(-m,H+m)}else if(side===2){x=rand(-m,W+m);y=H+m}else{x=-m;y=rand(-m,H+m)}const r=Math.random();let type=r<.62?'grunt':r<.82?'runner':r<.94?'brute':'ranged';const scale=1+wave*.045;let e={x,y,type,r:type==='brute'?26:type==='runner'?14:17,hp:30*scale,maxHp:0,speed:type==='runner'?150:type==='brute'?48:78,shoot:1.6,hit:0};if(type==='brute')e.hp*=3.5;if(type==='runner')e.hp*=.7;if(type==='ranged'){e.hp*=1.2;e.speed=55}e.maxHp=e.hp;enemies.push(e)}
function burst(x,y,n,color='#fff'){for(let i=0;i<n;i++){let a=rand(0,Math.PI*2),s=rand(40,240);particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:rand(.2,.7),max:.7,size:rand(1,5),color})}}
function attack(){if(state!=='playing'||player.attackCd>0)return;player.attackCd=player.attackRate;let dx=mouse.x-player.x,dy=mouse.y-player.y,l=Math.hypot(dx,dy)||1;dx/=l;dy/=l;const ang=Math.atan2(dy,dx);slashes.push({x:player.x,y:player.y,ang,life:.16});burst(player.x+dx*30,player.y+dy*30,8,'#b967ff');shake=4;for(const e of [...enemies]){let ex=e.x-player.x,ey=e.y-player.y,d=Math.hypot(ex,ey)||1,ea=Math.atan2(ey,ex),diff=Math.atan2(Math.sin(ea-ang),Math.cos(ea-ang));if(d<player.range+e.r&&Math.abs(diff)<1.05){let dmg=player.damage*(Math.random()<player.crit?2.2:1);e.hp-=dmg;floatText(e.x,e.y-22,'-'+Math.round(dmg));burst(e.x,e.y,6,'#fff');if(e.hp<=0)killEnemy(e)}}}
function killEnemy(e){const i=enemies.indexOf(e);if(i>=0)enemies.splice(i,1);kills++;waveKills++;player.special=Math.min(100,player.special+10);player.hp=Math.min(player.maxHp,player.hp+2);xp+=e.type==='brute'?20:10;burst(e.x,e.y,18,e.type==='brute'?'#d94cff':'#b967ff');if(xp>=xpNeed){xp-=xpNeed;xpNeed=Math.floor(xpNeed*1.3);showUpgrade()}}
function dash(){if(state!=='playing'||player.dashCd>0)return;let dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),dy=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);if(!dx&&!dy){dx=mouse.x-player.x;dy=mouse.y-player.y}let l=Math.hypot(dx,dy)||1;player.x=Math.max(25,Math.min(W-25,player.x+dx/l*150));player.y=Math.max(25,Math.min(H-25,player.y+dy/l*150));player.dashCd=player.dashMax;player.inv=.25;burst(player.x,player.y,30,'#b967ff');shake=10}
function special(){if(state!=='playing'||player.special<100)return;player.special=0;shake=18;burst(player.x,player.y,100,'#3a86ff');for(const e of [...enemies]){if(Math.hypot(e.x-player.x,e.y-player.y)<280){e.hp-=180;if(e.hp<=0)killEnemy(e)}}}
function hurt(n){if(player.inv>0)return;player.hp-=n;player.inv=.25;shake=8;burst(player.x,player.y,12,'#ff3d6e');if(player.hp<=0)endGame()}
function endGame(){state='over';$('finalWave').textContent=wave;$('finalKills').textContent=kills;$('finalTime').textContent=formatTime(timeAlive);$('gameOver').classList.remove('hidden')}
function showUpgrade(){state='upgrade';const pool=[['SHARP EDGE','+25% sword damage',()=>player.damage*=1.25],['SHADOW STEP','faster dash',()=>player.dashMax*=.8],['DARK VITALITY','+30 max HP',()=>{player.maxHp+=30;player.hp=player.maxHp}],['SWIFT BLADE','faster attacks',()=>player.attackRate*=.82],['LONG REACH','+20 sword range',()=>player.range+=20],['CRITICAL','+10% critical chance',()=>player.crit+=.1]];const choices=[];while(choices.length<3){const c=pool[Math.floor(Math.random()*pool.length)];if(!choices.includes(c))choices.push(c)}$('upgradeChoices').innerHTML=choices.map((c,i)=>`<button class="upgrade"><strong>${c[0]}</strong><span>${c[1]}</span></button>`).join('');document.querySelectorAll('.upgrade').forEach((b,i)=>b.onclick=()=>{choices[i][2]();$('upgradeScreen').classList.add('hidden');state='playing'}) ;$('upgradeScreen').classList.remove('hidden')}
function floatText(x,y,t){floats.push({x,y,t,life:1})}
function formatTime(t){return String(Math.floor(t/60)).padStart(2,'0')+':'+String(Math.floor(t%60)).padStart(2,'0')}
function update(dt){if(state!=='playing')return;timeAlive+=dt;player.attackCd=Math.max(0,player.attackCd-dt);player.dashCd=Math.max(0,player.dashCd-dt);player.inv=Math.max(0,player.inv-dt);let mx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),my=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0),l=Math.hypot(mx,my);if(l){mx/=l;my/=l;player.x+=mx*player.speed*dt;player.y+=my*player.speed*dt}player.x=Math.max(20,Math.min(W-20,player.x));player.y=Math.max(20,Math.min(H-20,player.y));if(mouse.down)attack();if(keys[' ']){keys[' ']=false;dash()}if(keys.shift){keys.shift=false;dash()}if(keys.q){keys.q=false;special()}spawnTimer-=dt;if(spawnTimer<=0){spawnEnemy();if(wave>10&&Math.random()<.2)spawnEnemy();spawnTimer=Math.max(.22,1.15-wave*.02)}for(const e of enemies){e.hit=Math.max(0,e.hit-dt);let dx=player.x-e.x,dy=player.y-e.y,d=Math.hypot(dx,dy)||1;if(e.type==='ranged'&&d<330){e.shoot-=dt;if(e.shoot<=0){shots.push({x:e.x,y:e.y,vx:dx/d*190,vy:dy/d*190,life:2});e.shoot=1.7}}else{e.x+=dx/d*e.speed*dt;e.y+=dy/d*e.speed*dt}if(d<e.r+player.r+3)hurt((e.type==='brute'?18:7)*dt*7)}for(const s of shots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;if(Math.hypot(s.x-player.x,s.y-player.y)<player.r+7){s.life=0;hurt(10+wave*.4)}}shots=shots.filter(s=>s.life>0);for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.94;p.vy*=.94;p.life-=dt}particles=particles.filter(p=>p.life>0);slashes.forEach(s=>s.life-=dt);slashes=slashes.filter(s=>s.life>0);floats.forEach(f=>{f.y-=25*dt;f.life-=dt});floats=floats.filter(f=>f.life>0);if(waveKills>=8+wave*2){wave++;waveKills=0;message('WAVE '+wave,1);if(wave%10===0){enemies.push({x:W/2,y:-70,type:'boss',r:48,hp:1200+wave*180,maxHp:1200+wave*180,speed:40,shoot:1,hit:0});message('BOSS INCOMING',1.5)}}updateHUD()}
function updateHUD(){$('wave').textContent=wave;$('kills').textContent=kills;$('time').textContent=formatTime(timeAlive);$('hpBar').style.width=Math.max(0,player.hp/player.maxHp*100)+'%';$('xpBar').style.width=Math.min(100,xp/xpNeed*100)+'%';$('specialBar').style.width=player.special+'%'}
function draw(){ctx.clearRect(0,0,W,H);ctx.save();ctx.translate(shake?rand(-shake,shake):0,shake?rand(-shake,shake):0);shake*=.88;let g=ctx.createRadialGradient(W/2,H/2,50,W/2,H/2,Math.max(W,H)*.7);g.addColorStop(0,'#151329');g.addColorStop(1,'#030409');ctx.fillStyle=g;ctx.fillRect(-30,-30,W+60,H+60);for(const s of stars){ctx.globalAlpha=s.a;ctx.fillStyle='#9b7cff';ctx.fillRect(s.x*W,s.y*H,s.s,s.s)}ctx.globalAlpha=1;ctx.strokeStyle='rgba(150,90,230,.08)';for(let x=0;x<W;x+=70){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=70){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}for(const s of shots){ctx.fillStyle='#ff5d8f';ctx.shadowBlur=15;ctx.shadowColor='#ff5d8f';ctx.beginPath();ctx.arc(s.x,s.y,5,0,7);ctx.fill();ctx.shadowBlur=0}for(const e of enemies)drawEnemy(e);for(const s of slashes){ctx.save();ctx.translate(s.x,s.y);ctx.rotate(s.ang);ctx.globalAlpha=s.life/.16;ctx.strokeStyle='#fff';ctx.shadowBlur=20;ctx.shadowColor='#b967ff';ctx.lineWidth=9;ctx.beginPath();ctx.arc(0,0,55,-.9,.9);ctx.stroke();ctx.restore()}drawPlayer();for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,7);ctx.fill()}for(const f of floats){ctx.globalAlpha=f.life;ctx.fillStyle='#fff';ctx.font='bold 14px Arial';ctx.textAlign='center';ctx.fillText(f.t,f.x,f.y)}ctx.restore();ctx.globalAlpha=1;if(msgTimer>0){msgTimer-=.016;$('message').textContent=msg;$('message').style.opacity=Math.min(1,msgTimer*3);if(msgTimer<=0)$('message').style.opacity=0}}
function drawPlayer(){const p=player;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(Math.atan2(mouse.y-p.y,mouse.x-p.x));ctx.globalAlpha=p.inv>0&&Math.floor(p.inv*20)%2===0?.35:1;ctx.shadowBlur=30;ctx.shadowColor='#9d4edd';ctx.fillStyle='#12101d';ctx.beginPath();ctx.arc(0,0,p.r,0,7);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#b967ff';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(5,-6,3,0,7);ctx.arc(5,6,3,0,7);ctx.fill();ctx.strokeStyle='#eee';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(12,0);ctx.lineTo(52,0);ctx.stroke();ctx.strokeStyle='#b967ff';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(18,-3);ctx.lineTo(54,-3);ctx.stroke();ctx.restore()}
function drawEnemy(e){ctx.save();ctx.translate(e.x,e.y);const c=e.type==='boss'?'#ff3d6e':e.type==='brute'?'#d94cff':e.type==='runner'?'#ffb84d':'#8d65ff';ctx.shadowBlur=e.type==='boss'?30:15;ctx.shadowColor=c;ctx.fillStyle='#100d19';ctx.beginPath();ctx.arc(0,0,e.r,0,7);ctx.fill();ctx.strokeStyle=c;ctx.lineWidth=e.type==='boss'?4:2;ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle=c;ctx.beginPath();ctx.arc(-e.r*.35,-3,3,0,7);ctx.arc(e.r*.35,-3,3,0,7);ctx.fill();if(e.type==='boss'){ctx.strokeStyle='#ff3d6e';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,e.r+8,0,7);ctx.stroke()}ctx.restore();if(e.type==='boss'||e.hp<e.maxHp){ctx.fillStyle='rgba(0,0,0,.5)';ctx.fillRect(e.x-e.r,e.y-e.r-12,e.r*2,5);ctx.fillStyle=c;ctx.fillRect(e.x-e.r,e.y-e.r-12,e.r*2*Math.max(0,e.hp/e.maxHp),5)}}
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;try{update(dt);draw()}catch(err){console.error('Shadow Arena error:',err);state='error';$('message').textContent='GAME ERROR — PRESS F5';$('message').style.opacity=1}requestAnimationFrame(loop)}
$('startBtn').onclick=startGame;$('restartBtn').onclick=startGame;$('dashBtn').onclick=dash;$('specialBtn').onclick=special;
// Always begin in the arena so a blank startup screen can never block the game.
startGame();
requestAnimationFrame(loop);
